### PR TITLE
Add Voice Input button to Message Box

### PR DESCRIPTION
**Pull request by koganei**
It uses the browser's SpeechRecognition API

### CODE REVIEW

**Comment by koganei** [comment]
My next step after this is to use the Speech synthesis to add to each message box from the AI.
And then the step after that is to do a 'hands free' mode to be able to have a conversation.

**Comment by enricoros** [comment]
This looks great! Maybe a function is missing? I'll test the parch locally as well. Such a great feature.

**Comment by enricoros** [comment]
Update: merging it.
 - I'm removing the microphone where 'isSpeechEnabled' = false (browser without support for the Speech API)
 - In turn React gives me a "hydration error"
 - So I'm creating a React hook "useSpeechRecognition()" which should solve this
 Just gonna take a little longer to finish the porting and test.
 Note: I'm actually porting with GPT4 - it knows way more than me.

**Comment by enricoros** [comment]
Merged! Please take a look, the change took a while, but was double-checked (if not authored) by gpt4 itself :)

**Comment by koganei** [comment]
Okay that's great. I thought about making that hook, but I didn't have as
much time as I wanted. Thank you for taking the time to enhancing the
feature!

**Pull request merged**
