### PR TITLE
Added support for GPT3.5 Turbo model

### PR DESCRIPTION
**Pull request by koganei**
Added support to pick the gpt-3.5-turbo model in the settings since I don't have access to gpt-4 yet.

### CODE REVIEW

**Comment by peperunas** [comment]
This solves part of #2.

**Comment by koganei** [comment]
I've tested it and it works for me. Can someone test that gpt-4 still works well?

**Comment by peperunas** [comment]
It would be good to reflect the name of the model in the page title as well

**Comment by koganei** [comment]
@peperunas Agreed. The title currently just doesn't exist. We could maybe have a larger conversation around what the title should be and whether the project needs a more identifiable name.

**Comment by peperunas** [comment]
I was thinking about having some kind of status indicator on the page as well, indicating the discussion's active model.

Somewhere around the bottom right corner of the page, maybe?

**Comment by enricoros** [comment]
Patch well done! Really needed.

**Pull request merged**
